# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
loom.allowMismatchedPlatformVersion = true
# Mod properties
mod_version = 1.0.0
maven_group = com.eirmax
archives_name = elytraswapperplus
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.10
#parchment_mapping_version = 2025.10.05

# Dependencies
fabric_loader_version = 0.18.1
fabric_api_version = 0.138.3+1.21.10
neoforge_version = 21.10.52-beta
