modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/eirmax/elytraswaperplus"
license = "MIT"

[[mods]]
modId = "elytraswaperplus"
version = "${version}"
displayName = "ElytraSwaperPlus"
authors = "eirmax,st0x0ef"
description = '''
A next generation mod that gives you the ability to quickly change your chestplate and elytra whenever you need it.
'''
#logoFile = ""

[[dependencies.elytraswaperplus]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.elytraswaperplus]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "elytraswaperplus.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
