modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/eirmax/elytraswapperplus"
license = "MIT"

[[mods]]
modId = "elytraswapperplus"
version = "${version}"
displayName = "elytraswapperplus"
authors = "eirmax, st0x0ef"
description = '''
A next generation mod that gives you the ability to quickly change your chestplate and elytra whenever you need it.
'''
logoFile = "assets/elytraswapperplus/icon.png"

[[dependencies.elytraswapperplus]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.elytraswapperplus]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "elytraswapperplus.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
